language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-strapforge' ]; then cd .. && eval "mv $currentfolder generator-strapforge" && cd generator-strapforge; fi
